import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { authApi } from '../api/auth';
import { useToast } from '../contexts/ToastContext';
import { Button } from '../components/common/Button';
import { Input } from '../components/common/Input';
import { ContactVerifier } from '../components/common/ContactVerifier';
import { KeyRound, User, Lock, ArrowLeft, ShieldCheck } from 'lucide-react';

export const RegisterInvitePage: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { showToast } = useToast();

  const [otp, setOtp] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [emailVerified, setEmailVerified] = useState(false);
  const [phoneVerified, setPhoneVerified] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const queryOtp = searchParams.get('otp');
    if (queryOtp) setOtp(queryOtp);
  }, [searchParams]);

  // At least one contact required; all filled contacts must be verified
  const hasAtLeastOneContact = email.trim() || phone.trim();
  const canSubmit =
    !!hasAtLeastOneContact &&
    (!email.trim() || emailVerified) &&
    (!phone.trim() || phoneVerified);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!otp.trim()) { showToast('Please enter your invitation OTP code', 'warning'); return; }
    if (!email.trim() && !phone.trim()) { showToast('Please enter at least one contact method (email or phone)', 'warning'); return; }
    if (email.trim() && !emailVerified) { showToast('Please verify your email address before submitting', 'warning'); return; }
    if (phone.trim() && !phoneVerified) { showToast('Please verify your phone number before submitting', 'warning'); return; }
    try {
      setIsLoading(true);
      await authApi.verifyRegisterOTP({
        otp: otp.trim(),
        me: {
          username: username.trim(),
          password,
          firstname: firstName.trim(),
          lastname: lastName.trim(),
          email: email.trim() || undefined,
          phone: phone.trim() || undefined,
        },
        username: username.trim(),
        password,
        firstname: firstName.trim(),
        lastname: lastName.trim(),
        email: email.trim() || undefined,
        phone: phone.trim() || undefined,
      });
      showToast('Registration complete! You can now log into your account.', 'success');
      navigate('/login');
    } catch (err: any) {
      showToast(err.message || 'Invitation verification failed', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col justify-center py-12 sm:px-6 lg:px-8 relative overflow-hidden">
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-gradient-to-tr from-emerald-600/10 to-blue-600/10 blur-[130px] rounded-full pointer-events-none" />
      <div className="sm:mx-auto sm:w-full sm:max-w-md text-center relative z-10">
        <Link to="/login" className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-200 mb-4 transition-colors">
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Login
        </Link>
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-emerald-600/20 border border-emerald-500/40 text-emerald-400 mb-2">
          <ShieldCheck className="w-6 h-6" />
        </div>
        <h2 className="text-2xl font-bold tracking-tight text-white">Join via Invitation</h2>
        <p className="mt-1 text-xs text-slate-400">Enter the invitation OTP code provided by your company admin</p>
      </div>
      <div className="mt-6 sm:mx-auto sm:w-full sm:max-w-md relative z-10">
        <div className="bg-slate-900/90 border border-slate-800 py-8 px-6 shadow-2xl rounded-2xl sm:px-10 backdrop-blur-xl">
          <form onSubmit={handleSubmit} className="space-y-4">
            <Input label="Invitation OTP Code" value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="e.g. 123456" required leftIcon={<KeyRound className="w-4 h-4 text-emerald-400" />} helperText="This single-use code was generated by your company Super Admin" />
            <div className="grid grid-cols-2 gap-3">
              <Input label="First Name" value={firstName} onChange={(e) => setFirstName(e.target.value)} placeholder="Jane" required />
              <Input label="Last Name" value={lastName} onChange={(e) => setLastName(e.target.value)} placeholder="Doe" required />
            </div>
            <Input label="Choose Username" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="janedoe" required leftIcon={<User className="w-4 h-4 text-slate-500" />} />
            <Input label="Set Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" required leftIcon={<Lock className="w-4 h-4 text-slate-500" />} />
            <ContactVerifier type="email" label="Email Address" value={email} onChange={setEmail} isVerified={emailVerified} onVerified={setEmailVerified} placeholder="jane@company.com" />
            <ContactVerifier type="phone" label="Phone Number" value={phone} onChange={setPhone} isVerified={phoneVerified} onVerified={setPhoneVerified} placeholder="+989123456789" />
            {!canSubmit && hasAtLeastOneContact && (
              <p className="text-center text-[11px] text-amber-400 flex items-center justify-center gap-1.5">
                <span>⚠</span> Please verify all entered contact details before creating your account.
              </p>
            )}
            <Button type="submit" variant="primary" className="w-full mt-4" isLoading={isLoading} disabled={isLoading || !canSubmit}>
              Verify Code & Create Account
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
};