import { Permission, PermissionAction, UserRole } from '../types/rbac';

export const ROLE_POLICIES: Record<UserRole, Permission[]> = {
  'super-admin': [
    { endpoint: '/api/v1/broadcast', method: 'POST' },
    { endpoint: '/api/v1/broadcast/:id', method: 'PUT' },
    { endpoint: '/api/v1/broadcast/:id', method: 'DELETE' },
    { endpoint: '/api/v1/broadcast/batch', method: 'DELETE' },

    { endpoint: '/api/v1/chats', method: 'GET' },
    { endpoint: '/api/v1/chats/:id', method: 'GET' },
    { endpoint: '/api/v1/chats/:id', method: 'PUT' },
    { endpoint: '/api/v1/chats/:id', method: 'DELETE' },
    { endpoint: '/api/v1/chats/:id/history', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id', method: 'DELETE' },
    { endpoint: '/api/v1/chats/otp/send', method: 'POST' },

    { endpoint: '/api/v1/attachments', method: 'GET' },
    { endpoint: '/api/v1/attachments/by-messages', method: 'POST' },
    { endpoint: '/api/v1/attachments/by-platform-file/:platform_file_id', method: 'GET' },
    { endpoint: '/api/v1/attachments/batch', method: 'DELETE' },
    { endpoint: '/api/v1/attachments/:id', method: 'GET' },
    { endpoint: '/api/v1/attachments/:id', method: 'PUT' },
    { endpoint: '/api/v1/attachments/:id/thumbnail', method: 'PATCH' },
    { endpoint: '/api/v1/attachments/:id', method: 'DELETE' },
    { endpoint: '/api/v1/attachments/:id/restore', method: 'POST' },
    { endpoint: '/api/v1/attachments/:id/links/download', method: 'POST' },
    { endpoint: '/api/v1/attachments/:id/links/download/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/links/download', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/links/download/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'DELETE' },

    { endpoint: '/api/v1/users/me', method: 'GET' },
    { endpoint: '/api/v1/companies/me', method: 'GET' },

    { endpoint: '/api/v1/companies/users/send-register-otp', method: 'POST' },
    { endpoint: '/api/v1/companies/:id', method: 'PUT' },
    { endpoint: '/api/v1/companies/:id', method: 'DELETE' },

    { endpoint: '/api/v1/users', method: 'GET' },
    { endpoint: '/api/v1/users/:id', method: 'GET' },
    { endpoint: '/api/v1/users/:id', method: 'PUT' },
    { endpoint: '/api/v1/users/:id/email', method: 'PUT' },
    { endpoint: '/api/v1/users/:id/phone', method: 'PUT' },
    { endpoint: '/api/v1/users/:id/username', method: 'PUT' },
    { endpoint: '/api/v1/users/:id/roles', method: 'PUT' },
    { endpoint: '/api/v1/users/:id', method: 'DELETE' },
  ],
  admin: [
    { endpoint: '/api/v1/broadcast', method: 'POST' },
    { endpoint: '/api/v1/broadcast/:id', method: 'PUT' },
    { endpoint: '/api/v1/broadcast/:id', method: 'DELETE' },
    { endpoint: '/api/v1/broadcast/batch', method: 'DELETE' },

    { endpoint: '/api/v1/chats', method: 'GET' },
    { endpoint: '/api/v1/chats/:id', method: 'GET' },
    { endpoint: '/api/v1/chats/:id', method: 'PUT' },
    { endpoint: '/api/v1/chats/:id', method: 'DELETE' },
    { endpoint: '/api/v1/chats/:id/history', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id', method: 'DELETE' },
    { endpoint: '/api/v1/chats/otp/send', method: 'POST' },

    { endpoint: '/api/v1/attachments', method: 'GET' },
    { endpoint: '/api/v1/attachments/by-messages', method: 'POST' },
    { endpoint: '/api/v1/attachments/by-platform-file/:platform_file_id', method: 'GET' },
    { endpoint: '/api/v1/attachments/batch', method: 'DELETE' },
    { endpoint: '/api/v1/attachments/:id', method: 'GET' },
    { endpoint: '/api/v1/attachments/:id', method: 'PUT' },
    { endpoint: '/api/v1/attachments/:id/thumbnail', method: 'PATCH' },
    { endpoint: '/api/v1/attachments/:id', method: 'DELETE' },
    { endpoint: '/api/v1/attachments/:id/restore', method: 'POST' },
    { endpoint: '/api/v1/attachments/:id/links/download', method: 'POST' },
    { endpoint: '/api/v1/attachments/:id/links/download/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/links/download', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments/links/download/batch', method: 'POST' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'GET' },
    { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'DELETE' },

    { endpoint: '/api/v1/users/me', method: 'GET' },
    { endpoint: '/api/v1/companies/me', method: 'GET' },
  ],
};

export const ACTION_TO_PERMISSION: Record<PermissionAction, Permission> = {
  'company:read': { endpoint: '/api/v1/companies/me', method: 'GET' },
  'company:update': { endpoint: '/api/v1/companies/:id', method: 'PUT' },
  'company:delete': { endpoint: '/api/v1/companies/:id', method: 'DELETE' },
  'company:invite': { endpoint: '/api/v1/companies/users/send-register-otp', method: 'POST' },

  'users:read': { endpoint: '/api/v1/users', method: 'GET' },
  'users:create': { endpoint: '/api/v1/companies/users/send-register-otp', method: 'POST' },
  'users:update': { endpoint: '/api/v1/users/:id', method: 'PUT' },
  'users:update_roles': { endpoint: '/api/v1/users/:id/roles', method: 'PUT' },
  'users:update_email': { endpoint: '/api/v1/users/:id/email', method: 'PUT' },
  'users:update_phone': { endpoint: '/api/v1/users/:id/phone', method: 'PUT' },
  'users:update_username': { endpoint: '/api/v1/users/:id/username', method: 'PUT' },
  'users:delete': { endpoint: '/api/v1/users/:id', method: 'DELETE' },

  'chats:read': { endpoint: '/api/v1/chats', method: 'GET' },
  'chats:create': { endpoint: '/api/v1/chats/otp/send', method: 'POST' },
  'chats:update': { endpoint: '/api/v1/chats/:id', method: 'PUT' },
  'chats:delete': { endpoint: '/api/v1/chats/:id', method: 'DELETE' },
  'chats:link_otp': { endpoint: '/api/v1/chats/otp/send', method: 'POST' },

  'history:read': { endpoint: '/api/v1/chats/:id/history', method: 'GET' },
  'history:delete': { endpoint: '/api/v1/chats/:id/history/:message_id', method: 'DELETE' },

  'broadcast:send': { endpoint: '/api/v1/broadcast', method: 'POST' },
  'broadcast:update': { endpoint: '/api/v1/broadcast/:id', method: 'PUT' },
  'broadcast:delete': { endpoint: '/api/v1/broadcast/:id', method: 'DELETE' },

  'attachments:read': { endpoint: '/api/v1/attachments', method: 'GET' },
  'attachments:create': { endpoint: '/api/v1/chats/:id/history/:message_id/attachments', method: 'POST' },
  'attachments:update': { endpoint: '/api/v1/attachments/:id', method: 'PUT' },
  'attachments:delete': { endpoint: '/api/v1/attachments/:id', method: 'DELETE' },

  'profile:read': { endpoint: '/api/v1/users/me', method: 'GET' },
  'profile:update': { endpoint: '/api/v1/users/me', method: 'GET' },
};